version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.java
    environment:
      - SERVER_PORT=8080
      - AUTH_URL=http://authenticator-backend:8081/api/v2/systemAuth/token
      - API_KEY=Sample-APIKey1
    ports:
      - "8080:8080"
    networks:
      - container-link
    depends_on:
      - mock-server
  mock-server:
    build:
      context: .
      dockerfile: Dockerfile.mockserver
    ports:
      - "4010:4010"
    networks:
      - container-link
networks:
  container-link:
    name: docker.internal
